language: python
python:
- 3.6
install: pip install -r requirements.txt
script:
- echo "skipping tests"
deploy:
  provider: heroku
  api_key:
    secure: c776qSzpBPJFc6CbLO0zJ0Y/+uJLItnbkQgYJrHkiuBy5+e+wrbeAqydZuhwfQMhGL0y6FKAKabdQxVhLgU4Pk73sc2KKMVVZDomea49kh4wUtfEnjMcd38Ey3mxvVe0qjWwGjQN/ir4n/mp0Eiq/D3pjFoEMcd8xZuPgeeM1dy/OajuKzd3dZQs2lxdlSUf82mW/bOn8iBwKFJ4Nn/ix32lYsrMXGsWEZz9zoBmtS5en+Cri0lyDTQlqdTOL3ef645lLKYcM+hK41JtOuEua1BRjvLCnh4PpC8jIRFq8uTUXUyY1TYU56sQT2W7yg5D/aiCsvgrNtdnib0x+w2EJln+vco2EeLTxpE6sHIRy9AByNTr4+ZsUIBbZj6TXALfGLZ/38HL6zf33J4PYm3KKdtVTPGfiFC548PI9AXZxqvrSI/aFWNLxrzDGNnxuS83dCLmm9xXvRxgKseSFC3GD/WojKGZq8FCoA2+9G+LmhPbY8iAmHh+26fhEa79Fvpu/Ktnr2UHQ2EVrNi1b8h4iI8YK0yYWir85YveojHgn4wjaRqKK0kKftRggrqw483tKD/TKfxpbdz5kWiu5RItPCWJyQvrN+Y2B/xI80SntGLX0NavWJXYGQ6fK8aKEjjda9H9yKDr8f+Fg3XaC8uODaIjN8dZhS+QHs9eH2LgT9s=
  app: yuntemp
  on:
    repo: synqs/YunTemp
